### ISSUE TITLE
Native CodePipline steps

### ISSUE THREAD

**Issue by sholtomaud** [awslabs/cloudfront-hosting-toolkit#17]
### Use case

granted this seems to be beta phase in development, but it would be good to remove the step functions from the pipeline 
![image](https://github.com/awslabs/cloudfront-hosting-toolkit/assets/398402/8e53d11d-e074-4b4e-bf94-25da783a60c3)

### Solution/User Experience

step functions in pipelines are a temporary solution to something that should be  native/built-in steps/actions in CodePipeline. 

This will make for a more standard pipeline flow without the need for custom step functions.

[Action structure reference](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference.html)
```yaml

ActionTypeId:
      Category: Invoke
      Owner: AWS
      Version: 1
      Provider: CloudFrontHosting    
Configuration:
      CloudFrontHostingAction: UpdateKeyValue

ActionTypeId:
      Category: Invoke
      Owner: AWS
      Version: 1
      Provider: CloudFrontHosting    
Configuration:
      CloudFrontHostingAction: Purge


## Or a simple consolidated action
ActionTypeId:
      Category: Invoke
      Owner: AWS
      Version: 1
      Provider: CloudFrontHosting    
Configuration:
      Phase: alpha|beta|prod

```

### Additional questions
 How does canary/blue-green work with the pipelines?
